spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8027

logging:
  file:
    name: logs/javareactapp.log
    path: javareactapp
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























